### ISSUE TITLE
Question about ServerAdmin?

### ISSUE THREAD

**Issue by hh-project-config** [worldpeaceio/wordpress-integration#11]
Thanks for providing the container! 

I am doing a research aiming at finding issues in configuration files. After pulling the image we notice that `ServerAdmin` is set to `webmaster@localhost` in `/etc/apache2/sites-enabled/000-default.conf`.  

However, the HttpD [official document](https://httpd.apache.org/docs/2.4/mod/core.html#servername) recommends the following config:
*  `ServerAdmin`: "However, it's recommended to actually use an email address, since there are a lot of CGI scripts that make that assumption. "

Could you please provide a knob to specify the value of `ServerAdmin`?

**Comment by nateinaction** [comment]
Hey @hh-project-config I think the best knob to turn here is to create a docker image based off of this one where you add an apache config for a new site or modify the default one.
